[package]
name = "half16equiv"
version = "0.1.0"
authors = ["Mark Stanislaw Baranowski <mark.s.baranowski@gmail.com>"]

[dependencies]
#half = "1.3.0"


[dependencies.half]
features = ["std"]
#features = ["std","use-intrinsics"]
